version: '3.7'

networks:
    backup: {}

services:

    tailscale:
        image: jonoh/tailscale:1.12.3
        devices:
            - /dev/net/tun:/dev/net/tun
        volumes:
            - /mnt/data/tailscale:/var/lib/tailscale
        network_mode: host
        privileged: true
        environment:
            - AUTH_KEY=${TAILSCALE_AUTH_KEY}
        command: --hostname=larry --exit-node
        restart: always

    rclone_serve_backup:
        image: rclone/rclone:1.56.0
        volumes:
            - /mnt/data/rclone_serve_backup:/config
            - /tmp/caches/rclone_serve_backup:/root/.cache
            - ./config/rclone_serve_backup/entrypoint.sh:/entrypoint.sh
        entrypoint: /entrypoint.sh
        environment: 
            - RCLONE_CONFIG_SEED=${RCLONE_CONFIG_SEED}
            - RCLONE_SOURCE=jotta:/backup
        restart: always
        networks:
            - backup

    duplicacy_naspool:
        image: jonoh/duplicacy:2.7.2
        environment:
            - BACKUP_CRON=1 * * * *
            - RUN_JOB_IMMEDIATELY=yes
            - PRUNE_CRON=34 1 * * sun
            - SNAPSHOT_ID=larry
            - DUPLICACY_PASSWORD=${DUPLICACY_PASSWORD}
            - STORAGE_URL=sftp://rclone_serve_backup:2022//duplicacy
            - JOB_RANDOM_DELAY=300
            - PRUNE_KEEP_POLICIES=0:360;30:180;7:30;1:7
        volumes:
            - /mnt/data:/data
            - /mnt/data/duplicacy_naspool/config:/config
        restart: always
        networks:
            - backup

    plex:
        image: jonoh/nas-plex:v0.0.29
        environment:
            - TZ=Pacific/Auckland
            - HOSTNAME=larry
            - PLEX_CLAIM=${PLEX_CLAIM}
            - INCOMING_DIR=/data/incoming
            - RCLONE_MOUNT_DIR=jotta:/plex-media
            - RCLONE_MOUNT_CACHE_DIR=/caches/rclone_plex
            - RCLONE_MOUNT_TARGET=/data/plex-media
            - FILEBOT_TMP_OUTPUT=/data/filebot-temp
        ports: 
            - 32400:32400
        volumes:
            - /mnt/data/plex:/config
            - /tmp/plex-transcode:/transcode
            - /tmp/plex:/tmp
            - /tmp/caches/plex:/caches
            - /tmp/filebot:/data/filebot-temp
        restart: always
        cap_add:
            - SYS_ADMIN
        devices:
            - /dev/fuse
        security_opt:
            - apparmor:unconfined

    cloudflare_plex:
        image: jonoh/cloudflared:2021.8.1
        volumes:
            - /mnt/data/cloudflare_plex:/home/nonroot/.cloudflared
        environment:
            - TZ=Pacific/Auckland
            - NO_AUTOUPDATE=true
            - TUNNEL_URL=http://plex:32400
            - CF_TUNNEL_ID=${CF_TUNNEL_ID}
        restart: always
        command: tunnel run ${CF_TUNNEL_ID}
