version: '3.7'

networks:
    backup: {}

# Images which require special regex handling for renovate
x-images:
    # Hardcodes version 3 because only 3 version parts are supported
    # renovate: versioning=regex:^3\.(?<major>\d+)\.(?<minor>\d+)\.(?<patch>\d+)-ls\d+$
    - &SONARR_IMAGE linuxserver/sonarr:3.0.6.1265-ls111
    # renovate: versioning=regex:^v(?<major>\d+)\.(?<minor>\d+)\.(?<patch>\d+)-ls\d+$
    - &JACKETT_IMAGE linuxserver/jackett:v0.18.407-ls36

x-base: &base
    depends_on: [cloudflare_dns]
    dns: cloudflare_dns
    restart: always

services:

    cloudflare_dns:
        image: jonoh/cloudflared:2021.8.2
        command: proxy-dns --address 0.0.0.0

    tailscale:
        << : *base
        image: jonoh/tailscale:1.12.3
        devices:
            - /dev/net/tun:/dev/net/tun
        volumes:
            - /mnt/data/tailscale:/var/lib/tailscale
        network_mode: host
        privileged: true
        environment:
            - AUTH_KEY=${TAILSCALE_AUTH_KEY}
        command: --hostname=larry --exit-node

    rclone_serve_backup:
        << : *base
        image: rclone/rclone:1.56.0
        volumes:
            - /mnt/data/rclone_serve_backup:/config
            - /tmp/caches/rclone_serve_backup:/root/.cache
            - ./config/rclone_serve_backup/entrypoint.sh:/entrypoint.sh
        entrypoint: /entrypoint.sh
        environment: 
            - RCLONE_CONFIG_SEED=${RCLONE_CONFIG_SEED}
            - RCLONE_SOURCE=jotta:/backup
        networks:
            - backup

    duplicacy:
        << : *base
        image: jonoh/duplicacy:2.7.2
        environment:
            - BACKUP_CRON=1 * * * *
            - RUN_JOB_IMMEDIATELY=yes
            - PRUNE_CRON=34 1 * * sun
            - SNAPSHOT_ID=larry
            - DUPLICACY_PASSWORD=${DUPLICACY_PASSWORD}
            - STORAGE_URL=sftp://rclone_serve_backup:2022//duplicacy
            - JOB_RANDOM_DELAY=300
            - PRUNE_KEEP_POLICIES=0:360;30:180;7:30;1:7
            - PRE_BACKUP_SCRIPT=/usr/local/bin/pre_backup.sh
        volumes:
            - /mnt/data:/data
            - /mnt/data/duplicacy_naspool/config:/config
            - ./config/duplicacy/pre_backup.sh:/usr/local/bin/pre_backup.sh
        networks:
            - backup

    plex:
        << : *base
        image: jonoh/nas-plex:v0.0.36
        environment:
            - TZ=Pacific/Auckland
            - HOSTNAME=larry
            - PLEX_CLAIM=${PLEX_CLAIM}
            - INCOMING_DIR=/data/incoming
            - RCLONE_MOUNT_DIR=jotta:/plex-media
            - RCLONE_MOUNT_CACHE_DIR=/caches/rclone_plex
            - RCLONE_MOUNT_TARGET=/data/plex-media
            - RCLONE_CACHE_MAX_SIZE=25G
        ports: 
            - 32400:32400
        volumes:
            - /mnt/data/plex:/config
            - /tmp/plex-transcode:/transcode
            - /tmp/plex:/tmp
            - /tmp/caches/plex:/caches/rclone_plex
        cap_add:
            - SYS_ADMIN
        devices:
            - /dev/fuse
        security_opt:
            - apparmor:unconfined

    cloudflare_plex:
        << : *base
        image: jonoh/cloudflared:2021.8.2
        volumes:
            - /mnt/data/cloudflare_plex:/home/nonroot/.cloudflared
        environment:
            - TZ=Pacific/Auckland
            - NO_AUTOUPDATE=true
            - TUNNEL_URL=http://plex:32400
            - CF_TUNNEL_ID=${CF_TUNNEL_ID}
        command: tunnel run ${CF_TUNNEL_ID}

    getflix_proxy:
        << : *base
        image: jonoh/openvpn-socks:2.5.2
        cap_add:
            - NET_ADMIN
        devices:
            - /dev/net/tun
        environment:
            - OPENVPN_USERNAME=${GETFLIX_USERNAME}
            - OPENVPN_PASSWORD=${GETFLIX_PASSWORD}
        volumes:
            - ./config/getflix_proxy/config.ovpn:/config/config.ovpn
        ports:
            - 1080:1080

    rclone_move_media:
        << : *base
        image: rclone/rclone:1.55.1
        volumes:
            - /mnt/tmp/plex-media:/source
            - /mnt/data/rclone_move_media:/config
            - ./config/rclone_move_media/entrypoint:/entrypoint
        environment:
            - RCLONE_CONFIG_SEED=${RCLONE_MOVE_MEDIA_CONF}
            - SOURCE=/source
            - DEST=jotta:/plex-media
        entrypoint: /entrypoint

    qbt:
        << : *base
        image: jonoh/nas-qbittorrent:v0.0.11
        environment:
            - TZ=Pacific/Auckland
            - WEBUI_PORT=443
            - PUID=1001
            - PGID=1001
        volumes:
            - /mnt/data/qbt:/config
            - /mnt/downloads:/downloads

    cloudflare_qbt:
        << : *base
        image: jonoh/cloudflared:2021.8.2
        volumes:
            - /mnt/data/cloudflare_qbt:/home/nonroot/.cloudflared
        environment:
            - TZ=Pacific/Auckland
            - NO_AUTOUPDATE=true
            - TUNNEL_URL=http://qbt:443
            - CF_QBT_TUNNEL_ID=${CF_QBT_TUNNEL_ID}
        command: tunnel run ${CF_QBT_TUNNEL_ID}

    jackett:
        << : *base
        image: *JACKETT_IMAGE
        volumes:
            - /mnt/data/jackett:/config
            - /tmp/jackett:/downloads
        environment:
            - PGID=1000
            - PUID=1000
            - TZ=Pacific/Auckland

    cloudflare_jackett:
        << : *base
        image: jonoh/cloudflared:2021.8.2
        volumes:
            - /mnt/data/cloudflare_jackett:/config
        environment:
            - TZ=Pacific/Auckland
            - TUNNEL_URL=http://jackett:9117
            - ACCOUNT_ID=${CF_ACCOUNT_ID}
            - TUNNEL_NAME=jackett
            - TUNNEL_ID=${JACKETT_TUNNEL_ID}
            - TUNNEL_SECRET=${JACKETT_TUNNEL_SECRET}


